# Generated by Django 4.2.9 on 2024-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="core.tags"),
        ),
    ]
